### PR TITLE
Added PHP utility class containing in-built model and view to construct ...

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Not sure if this fits in with the project, but I thought I'd add it anyway... I will also publish a js fix soon
...UI element

Taken from CD2 UI Utilities, thought I would de-couple from any framework specifics, and provide for anyone to use... If you use smarty, codeIgniter, laravel etc, it will return a string you can send to the view and is object-based with minimal options. Javascript activation should be undertaken separately as this is merely for the DOM of the element...

### CODE REVIEW

**Comment by RhysC** [comment]
a PHP file in a javascript project that is server agnostic? I am not that it is a good idea.

**Comment by Lewiscowles1986** [comment]
Thats fine but it does not change the core project, it merely adds example code of how to integrate to a PHP project, so the core project still is platform agnostic...

**Comment by michaek** [comment]
I agree with @RhysC that a PHP example is too specific for what's currently a Javascript-only project.

**Comment by Lewiscowles1986** [comment]
okay lol completely forgot about this, I wouldn't worry just close it down

**Pull request closed without merging**
