### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by levieraf**
This is a good idea put these files out of this .gitignore, you will wish only make bower install ... and then add this css within your index.ext like other libraries that has this step done for you.

### CODE REVIEW

**Comment by mrhota** [comment]
I don't understand. I don't want to see .min.js and .min.css files in my repo. What is "index.ext"?

**Comment by levieraf** [comment]
Your library is great, what i try to say is that when someone want to use
your library we will prefer find the css and the js instead of make npm
install and them bower install and then grunt compileAll and then finally
use the css and js to include on your index.html or index.php or index.jsp
etc.

If you see tools like:

https://github.com/eternicode/bootstrap-datepicker or
https://github.com/jquery/jquery or
https://github.com/FortAwesome/Font-Awesome

You can see that these tools has its files css and js done to use.

It is my suggestion, your library is great

2015-08-12 11:56 GMT-05:00 A.J. notifications@github.com:

> I don't understand. I don't want to see .min.js and .min.css files in my
> repo. What is "index.ext"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jdewit/bootstrap-timepicker/pull/282#issuecomment-130369341
> .

## 

Atentamente,

Luis Viera
Panama: +507 60036763
Skype: levieraf

**Comment by mrhota** [comment]
Oh, I see what you mean now. I want to keep compilation artifacts out of the repo because it makes merging Pull Requests a nightmare.

You should download a release archive, because it will contain the css and js files you want.

Here's the relevant part from the `Status` section of the README:

> While the maintainers clean things up, it would be best if you download a release archive from the Releases tab instead of using the HEAD code.

The "Releases" tab is on the main page, above the file listing, in between "branches" and "contributors".

screen shot 2015-08-12 at 15 31 22

I will close this PR for now. Thank you for the contribution, though! Please let me know if you find defects in the released code, and issue more pull requests if you have the time.

**Comment by levieraf** [comment]
Ok no problem :)

Thanks!

**Pull request closed without merging**
