### PR TITLE
Update to Bootstrap 3.0

### PR DESCRIPTION
**Pull request by zzeneg**
Updating classes by migration guide in bootstrap docs and fixing some
css issues from 3.0.

### CODE REVIEW

**Comment by christianrojas** [comment]
:+1:

**Comment by mrkre** [comment]
:+1:  wondering why you did not change in the js:

``` [html]
<i class="glyphicons..."></i> into <span class="glyphicons..."></span> 
```

Thanks for fixing the items.

**Comment by zzeneg** [comment]
@mrkre oh, my. Just missed this tag in js, sorry:)

**Comment by zervoulakus** [comment]
time is not showing at bootstrap3
the picker-switch is not showing from the popup

**Comment by euskadi31** [comment]
:+1:

**Comment by TomasVotruba** [comment]
Ping

**Pull request closed without merging**
