### PR TITLE
Trigger change() of element on value update, fixed issue where time was not shown in 24-hour format

### PR DESCRIPTION
**Pull request by koenpunt**

### CODE REVIEW

**Comment by michelt** [comment]
You can either trigger it on hide function "hide" (l. 100) or in function "updateElement" (l. 172).

Just add this line :

this.$element.trigger('change');

**Comment by koenpunt** [comment]
@michelt If you look again you can see it isn't a feature request, it is a pull request. And indeed solved it by doing something like you suggested

**Comment by michelt** [comment]
@koenpunt Oh yes sorry. Thanks for the note back

**Comment by Nek-** [comment]
There is commented code in your PR, that's not cool.
But I agree with the rest.

**Pull request merged**
