### PR TITLE
Fix for bootstrap modals

### PR DESCRIPTION
**Pull request by oshoemaker**
Needed to increase z-index on the widget for it to pop over the the modal.

### CODE REVIEW

**Comment by oshoemaker** [comment]
https://github.com/jdewit/bootstrap-timepicker/issues/326

**Comment by oshoemaker** [comment]
Timepicker feature:: should place timepicker on top of parents: failed
  Expected '2050' to be '1010'. (1)

This would need an update to the unit tests.

**Comment by saibalroy** [comment]
bootstrap modal form jump on safari ipad.how to fix it?

**Comment by mrhota** [comment]
@oshoemaker please update the unit tests

**Comment by mrhota** [comment]
@oshoemaker I have a feeling this is not the correct fix.

First, why doesn't `widget.zindex = timepicker.zindex + 10` work? We know it works in some cases (like when there's no modal). Second, what makes you think `widget.zindex = timepicker.zindex + 1050` would work any better?

It seems more likely that the correct fix would set the widget's zindex as a function of the _modal and timepicker_ z-indices, but I don't have time to investigate. Would you be willing to look into that?

**Comment by oshoemaker** [comment]
Because I tested it and it worked. There are other issues with the UI so it will take much more work to try and make it work with a modal.

**Pull request closed without merging**
