### PR TITLE
Added useful info about time in show/hide timepicker event

### PR DESCRIPTION
**Pull request by tomasAlabes**
When receiving this events, I wanted not only the string with the time, but also the hours, minutes, seconds and meridian selected. Parsing the string was too dirty, so I added this data to the event.

Regards,
Tom

### CODE REVIEW

**Comment by jdewit** [comment]
I can see how that would be useful. 

Why put it in an object though. Why not just 

...
time: this.getTime(),
hour: this.hour,
mintute: this.minute

etc.

There's also another event (updateTime) that could use this. 

I'd be happy to merge this in before I tag a version today.

**Comment by tomasAlabes** [comment]
I thought of adding the values directly, but I think they form like a 'unit' of data. Also when I debugged the first time looking for this values, I had to look between all the other jquery data that comes inside the event. It looked cleaner this way.
I even thought of making 'time' an object and add a 'value' to return the 'hh:mm A' string, and hour, minute, etc to it. Like this: 

e.time.value; //today getTime(). 
e.time.hours;

Yes, that data would definitively be useful in the update event.

**Comment by jdewit** [comment]
Yeah I like that. 

e.time.value
e.time.hours
e.time.minutes 
etc. 

Care to redo your pull?

**Comment by tomasAlabes** [comment]
Ok, I'll do it. But remember I don't have the update event.

**Comment by jdewit** [comment]
my latest commit has a changeTime event which can benefit from this as well.

**Comment by tomasAlabes** [comment]
That last commit does what we talked about. After your 'changeTime' commit I can add it too if you want.

**Pull request merged**
