### PR TITLE
Added changeTime event

### PR DESCRIPTION
**Pull request by jalevin**
``` javascript
$('.timepicker').timepicker()
    .on('changeTime', function(ev) {
      alert('time has changed');
    });
```

### CODE REVIEW

**Comment by jdewit** [comment]
Can you add this to the docs as well.

**Comment by jalevin** [comment]
You bet. Done.

**Comment by mahhek** [comment]
Hey, I just replaced js file with the your version to get changeTime event but it is calling two times, can you please guide me why it is calling two times, thanks.

**Comment by jalevin** [comment]
The first call happens when the object is initiated. The second happens when the time changes, however, if you change AM/PM it fire twice. I'm digging around to see if I can put together a fix.

**Comment by mahhek** [comment]
Actually I didn't change AM/PM still it is giving two calls, and it give two simultaneous calls only on timeChange. Thanks again.

**Comment by jalevin** [comment]
@mahhek when I rebased my commits some old code was re-implemented. Latest version should be Kosher.

**Comment by jalevin** [comment]
@jdewit docs and js should be up-to-date.

**Comment by claytantor** [comment]
wow, why dont you merge this pull request? super important feature. I had use this pull request version over the one in master.  thanks jalevin fro the improvement.

**Comment by mariapaulinar** [comment]
Thank you so much. I was needing this feature to add hour validation :D

**Comment by benjaoming** [comment]
Please merge!!

**Comment by mariapaulinar** [comment]
Hey, above your comment jalevin shared the commit, download raw and enjoy :)

**Comment by benjaoming** [comment]
Yeah, but it's so useful, it should be merged into the @jdewit main tree!!

Anyways, I had to change:

```
time: this.time()
```

to

```
time: this.getTime()
```

...in order to use `ev.time` in my event handler.

**Comment by mariapaulinar** [comment]
Oh, I get it :D

**Comment by jdewit** [comment]
I'm in the process of making some big changes. Just use the fork for now. 

Timepicker will soon be tested with Jasmine and be built with grunt. Should be ready within the next few days.

**Comment by mariapaulinar** [comment]
@jdewit that's great news!

**Comment by jdewit** [comment]
Checkout the branch event-on-update. 

$('#timepicker').on('change', function() {
  console.log('time is = ' + $(this).val());
});

Let me know if this suits your needs.

@mariapaulinar. timepicker should validate input already. What is getting through?

**Comment by jalevin** [comment]
@jdewit 

Your commit does provide the same functionality that mine does, however, the syntax for adding a hook doesn't match up with the 'norm'. There are many other bootstrap widgets who detect change events with "changeWidget". In other words $('#datepicker').on('changeDate'......  I would prefer this syntax be keep to reduce ambiguity. Also, you asked me to update the docs, so even if you don't keep my changes I would appreciate if the pull request was accepted, merged, and then your changes applied.

**Comment by jdewit** [comment]
As far as I know a merge would be a nightmare. I like your syntax better on second thought. If you'd still like to contribute please make another pull request otherwise I can make the changes today since I'm still doing some more work on this project.

Let me know!

**Pull request closed without merging**
