### PR TITLE
Add dist/ folder to the source control 

### PR DESCRIPTION
**Pull request by ricardobrandao**
I am using [JSPM](http://jspm.io/) to deal with my client-side dependencies. Since I am trying to use the sources from the github repositories directly, I want to avoid compiling the .less files locally.

One possible solution is to create a dist/ folder with all the .js and .css files (both unminified and minified). Another possible solution is to add the css/ folder to the source control.

If this gets merged (or we add the css/ folder to the source control), I can add a package override for this project in the [JSPM registry](https://github.com/jspm/registry/).

### CODE REVIEW

**Comment by rougeth** [comment]
:+1:

**Comment by mrhota** [comment]
@ricardobrandao @rougeth I removed minified files from the repo a few months ago. Minified files are build artifacts. As such they do not belong in version control.

Is there some reason why you're pulling dependencies from github repos and NOT building them? What you're trying to do is analogous to depending on a C library, pulling its source, not compiling it, then filing an issue about how the binaries should be included in the repo.

I just perused the JSPM page. It says something about how JSPM can use a project's release archives when available. We have release archives with compiled and minified code. You should use those.

**Comment by mrhota** [comment]
Marking as `wontfix` unless someone can provide a compelling reason to include build artifacts in version control in lieu of already-provided release archives.

**Comment by ricardobrandao** [comment]
@mrhota thanks for the reply. Sorry, I haven't noticed that the release packages had the build artifacts (I looked inside git tags only).

I agree with you, build artifacts should **NOT** be on version control and using **releases** is a much better way of distributing stuff. However, I think that it might be useful for git **tags** to contain the build artifacts (take as an example [knockout](https://github.com/knockout/knockout/tree/v3.3.0) or [jquery](https://github.com/jquery/jquery/tree/2.1.4)).

**Pull request closed without merging**
