### PR TITLE
Prevent the entry of "wrong" characters in the fields

### PR DESCRIPTION
**Pull request by thiagotalma**

### CODE REVIEW

**Comment by eleumik** [comment]
@thiagotalma  How do you insert AM / PM ?

**Comment by thiagotalma** [comment]
It is more practical to use the arrow keys to select AM or PM. 

If it is a problem, just change the code to allow the [apm] keys

**Comment by tgirardi** [comment]
@thiagotalma: preventing wrong characters is a good idea, but I suggest the following improvements:
1. Take into account @eleumik's comment on AM / PM
2. event.charCode is deprecated (https://developer.mozilla.org/en-US/docs/Web/API/event.charCode), use keyCode instead.
3. Using regexp is too much of an overkill, it would be better just to check the keyCode
4. Once you start checking the keyCode you could notice that there is another keyCode verification taking place on line 1053. In order to avoid duplication of code, you should put that code on a method that can be called from both places.
5. Check the format. E.g: the code is currently using 2 spaces for indentation, while your code is using 4.

**Comment by thiagotalma** [comment]
Hello @tgirardi  
The important thing was the suggestion I made.
You can be free to close this PR and implement the way the team sees fit.

I will not be hurt  :)

**Comment by tgirardi** [comment]
@thiagotalma, in fact I'm very thankful for your contribution and was hoping if you could improve it in order to merge it :)

I'm a little short on time, so it would be great if you could give it those suggestions a try and make another commit on top of this branch. The users of this plugin will surely be very happy as it is indeed a very good idea what you are proposing

**Comment by eleumik** [comment]
Hi, I would be careful with input limitations that are usually not really understood by users (why I cannot write, Did my computer just hang?  http://ux.stackexchange.com/questions/39818/limiting-user-input-beneficial-or-user-annoyance ), for example HTML5 type='number' lets you write letters and only on submission tells you is not ok.  The worst case is when  for some not predicted case the user cannot insert correct stuff, support goes on fire ;-) The regex would be easy to fix but what if AM / PM literals become configurable for different locales ? I believe that the widget helps enough the user  and does not really need this change, at least should be an option.

**Comment by thiagotalma** [comment]
It was just a stupid suggestion, without any significant improvement.

**Pull request closed without merging**
